(define (make-vect x y) (cons x y))
(define (xcor-vect v) (car v))
(define (ycor-vect v) (cdr v))

(define (con-vect v) (make-vect (- xcor-vect v) (- ycor-vect v)))
(define (add-vect v1 v2)
  (make-vect (+ (xcor-vect v1) (xcor-vect v2)) (+ (ycor-vect v1) (ycor-vect v2)))
)
(define (sub-vect v1 v2)
  (add-vect v1 (con-vect v2))
)
(define (scale-vect s v)
  (make-vect (* (xcor-vect v) s) (* (ycor-vect v) s))
)
