; inside polynomial package
(define (div-terms l1 l2)
  (if (empty-list? l1) (list (empty-list) (empty-list))
    (let* ((t1 (first-term l1)) (t2 (first-term l2)) (o1 (order t1)) (o2 (order t2)))
      (if (< o1 o2)
        (list (empty-list) l1)
        (let* ((new-coe (div (coeff t1) (coeff t2))) (new-order (- o1 o2)) (new-term (make-term new-order new-coe)))
          (let ((rest-of-result (div-terms (sub-poly l1 (mul-term-by-all-terms new-term l2) l2))))
            (cons (adjoin-term new-term (car rest-of-result)) (cdr rest-of-result))
          )
        )
      )
    )
  )
)
