(define (probe name connector)
  (define (print-probe value)
    (newline)
    (display "Probe: ")(display name)(display " = ")(display value)(newline)
  )
  (define (process-new-value) (print-probe (get-value connector)))
  (define (process-forget-value) (print-probe "?"))
  (define (me request)
    (cond
      ((eq? request 'have-value) (process-new-value))
      ((eq? request 'lost-value) (process-forget-value))
      (else (error "Unknown request -- PROBE" request))
    )
  )
  (connect connector me)
  me
)
